[versions]
paper = "1.20.4-R0.1-SNAPSHOT"

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1"}